baseURL = 'https://stb.banghasan.com'
languageCode = 'en-us'
title = 'STB Dev'
theme = 'noteworthy-'

paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"

[author]
    name = "bangHasan"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
     math = true
    # Blog description at the top of the homepage. Supports markdown.
    description = "Mini Server dan Router dengan Budget Minimalis"

    # Main
    email = "banghasan@gmail.com"
    youtube = "https://www.youtube.com/banghasans"
    soundcloud = "https://soundcloud.com/hasanudin-h-syafaat"


    # Programming
    github = "https://github.com/banghasan"
    gitlab = "https://gitlab.com/banghasan"
    stackoverflow = "https://stackoverflow.com/users/13564539/hasanudin-h-syafaat"


# Menu links along the sidebar navigation.

[[menu.main]]
    identifier = "about"
    name = "ðŸ™‹ðŸ½ About"
    url = "/about/"
    weight = 10 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defi>

[[menu.main]]
    identifier = "tools"
    name = "âš™ï¸ Tools"
    url = "/tools/"
    weight = 20 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defi>

[[menu.main]]
    identifier = "tools-driver"
    name = "ã…¤ â”œ Driver"
    url = "/tools/driver/"
    weight = 21

[[menu.main]]
    identifier = "tools-burner-usb"
    name = "ã…¤ â”œ Burner USB"
    url = "/tools/burner/"
    weight = 22

[[menu.main]]
    identifier = "tools-burner-emmc"
    name = "ã…¤ â”œ Flashing MMC"
    url = "/tools/usb-burning-tool/"
    weight = 23

[[menu.main]]
    identifier = "armbian"
    name = "ã…¤ â”” Armbian"
    url = "/tools/armbian/"
    weight = 25

[[menu.main]]
    identifier = "tags"
    name = "ðŸ”– Tags"
    url = "/tags/"
    weight = 30

[[menu.main]]
    name = "ðŸ“‘ Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 40
